name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Message
        run: echo "Step 1 executed"

      - name: list files
        run: ls -la

      - name: Show current directory
        run: pwd

